[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/fW3GwKrWN9h32zTRhLgVzMhXCFWUDgX7"
  Md5 = "3cc9e066005c0178af670e31fbdf4ae1"
  Sha256 = "dd81fde5eea6c70d62188b4ec9b688228e72261bac8d5f9bf7cf4751292abf50"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/cLzS1fSfzY5Vyt77TjtMpuC5SPAXDi6U"
  Md5 = "f3c90452241aded7f8fd67bbae015082"
  Sha256 = "a0bf4413489d5e57253d9dd097ce2eded78ba46a05fda5dc22451ccd32452949"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/pTpUPdbSqBQhN97pAns2GwdQeC72WZMR"
  Md5 = "e8eff722e1bd8d9469f9d866bdcee423"
  Sha256 = "95949cbd1f95ba65cc4c24f8e71fad19c8b822404be0a85e0cc96ad2efe8d4f7"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
