[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/fW3GwKrWN9h32zTRhLgVzMhXCFWUDgX7"
  Md5 = "3cc9e066005c0178af670e31fbdf4ae1"
  Sha256 = "dd81fde5eea6c70d62188b4ec9b688228e72261bac8d5f9bf7cf4751292abf50"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/8kBCDWKJPR3Y47TK1vXGeqDSQdbupGsP"
  Md5 = "84887809d97e847300c16fd31c606d25"
  Sha256 = "f88a52079a6c01b0f3e2a1519c40d93a7246b1c91259d3c0f340f1d3e38e4ffe"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/X1Lz4LZSfQb7A3X2nyAPyxNNnr6k9Pv8"
  Md5 = "db4ca3970d700bdb5011083b774c67ee"
  Sha256 = "056cd01c08a480619b14cffbe71149f8c1902d859b60e824813fdff0ad12fff3"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
