[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/V9J59ifjfjSNHaevCsBE73mihFT8i5Rv"
  Md5 = "fde0c2675eb16f3a5db12ee6cbe0b390"
  Sha256 = "bd1871c3b6baaf42784b5087ab23e68128bf17ba64a1d421d04cb80bede23a1a"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/P8QuGAqveeaaJECvFzCyNJ3ffPjMrbeM"
  Md5 = "007fe827f10d6be9ec61d8a88727bd05"
  Sha256 = "5671ce8f187a80e125e6edd7e51cefd2765bfeb0907070f1f02d63f26cb80024"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/PkGtuWF7gejkAYDrN1dVtSeGdNsaBtXH"
  Md5 = "ec1db5966d7c5bc8e6d20f7f642c3b45"
  Sha256 = "6de58393c164a6d56958fe1fb85e4b95911ac7feb33af23769aa4e325bc55fe2"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
