[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/rKL1wqzXCVfUid6eg1yWdnaNHe4mHids"
  Md5 = "8a388d79b0489128e6e6697cfdcef96f"
  Sha256 = "f87c69932433d68664ae568dfc8ef588fc60f5ba406eddc166f83f298c94091d"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/PZaX22JCgMuAFvsHZT5A18KQFBVMDkxg"
  Md5 = "905be8eef44544be2d8cccc20e00d301"
  Sha256 = "6fac3984792cd3f1b4a9a37a5c85edf50607133f8ec56ef8259f0a7601661f39"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/2y4bN9exRnjfgDuazjjhW2BSMjWtdTJ7"
  Md5 = "75d5cb91d874977d399e3caf4141223f"
  Sha256 = "13cbe25d443574fa65dcc396046483f5c8de2ad94f52bf0fe1a8bff1db4273d1"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
