[server]
uri = "https://raw.githubusercontent.com/cootos/server/master/ZRUvSkSVQZikLSBFMjkDbrZCieFihLvz"
md5 = "ec3c8b249fd0351a94f3a2f2e7a10bdc"
sha256 = "52c68baeeb9b1ec1fac6bb4e8e41b68e390ad3e54dd9c059f9a38a07b1dd52be"

[rules]
uri = "https://raw.githubusercontent.com/cootos/server/master/VHTmXrWHiLXKiYCPrZzvEaxYgKbVBgni"
md5 = "7347538ef2cb0ad516ece8d9a8f88240"
sha256 = "f315c4a295125b76c10a5de8130c540467fd0f9dd47e7bfdcf98d602ef3893c0"

[geoip]
uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
sha256= ""
