[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/6SGSr495f5tz4Y7cnhUrz1yX4XHje8i8"
  Md5 = "c091db7d1007a49f65994fcad31d833b"
  Sha256 = "115b4e2bf4e3c0a3d1f8abca5328d49b7e2814a74a94d0a946203eeb91fe4b30"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/BMzBHTwZYLk2LyN5rU3YVgdCmkHFLFw5"
  Md5 = "72d5cf99b99635a1c245c71d82f584bb"
  Sha256 = "46ca735e7fc270f5fba8f1c76f0f8321a8600d9d04bb85362b14700fd2b5fa27"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/tBTWTcLkvQSx77SXFbBEz5TaqU8GLr7H"
  Md5 = "bc6e9c050ada13d7d268c969aa30aef7"
  Sha256 = "c0626bdfd151e7fa83ec9f0b7b39583d674e8130309af124a94ae608e5b47c76"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
