[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/U1sfHR89F3kG2qG8pxN9cHnPZ7dYi8Ap"
  Md5 = "0a3ff4eb7a7298d040e106dd59979d6b"
  Sha256 = "9d34946c562da55a7d62b0f376369dad9c0f26ec2624aba877a4fc8376e53561"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/gpbZhBN5f5gkBFqdXEtwM5mppHQBknVp"
  Md5 = "326942a7b1b3249612c8e1a06ff79930"
  Sha256 = "1f1f27d1bdc0c0d4c977e9982d659635c2c969c2ba86446dac173c591abf17bf"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/awXxfcMQrihvVE5L26TK9SNJwSGaNviq"
  Md5 = "cdef4616504dda12e5ef170db112b1e1"
  Sha256 = "e5db151d00ec3afd3e540b3144c931ed3fe14ec6edc720218b256e72a7deecec"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
