[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/fW3GwKrWN9h32zTRhLgVzMhXCFWUDgX7"
  Md5 = "3cc9e066005c0178af670e31fbdf4ae1"
  Sha256 = "dd81fde5eea6c70d62188b4ec9b688228e72261bac8d5f9bf7cf4751292abf50"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/G2DgcT9MBWFhYrWBtpZSiqZDnZQGHjXK"
  Md5 = "c42935419bff3559b02f1dd61152b865"
  Sha256 = "14980119d6f49bf1558406e1391ae4a4f8d60b61d28e367c38c039fdafa9cd2e"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/QqWh6S3DRURFYAYMP6d1YYc3NZdcNPqK"
  Md5 = "8b034cea59ea46b32c498d1f11499fa2"
  Sha256 = "e82abf8dd49129619cc1f9e7867c5520a83a3cead3d9d4c62491046289cdf7b9"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
