[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/kjTLrBmEHTLhuzKft5ZZi7zLGUDiK1GM"
  Md5 = "0886c8e80056b4a0c94355787bab8b92"
  Sha256 = "ae6c37ed6b2dd53280641663493a8c4d9ea5f4c27f69e13d7b26c57a29ba93fe"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/gpbZhBN5f5gkBFqdXEtwM5mppHQBknVp"
  Md5 = "326942a7b1b3249612c8e1a06ff79930"
  Sha256 = "1f1f27d1bdc0c0d4c977e9982d659635c2c969c2ba86446dac173c591abf17bf"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/awXxfcMQrihvVE5L26TK9SNJwSGaNviq"
  Md5 = "cdef4616504dda12e5ef170db112b1e1"
  Sha256 = "e5db151d00ec3afd3e540b3144c931ed3fe14ec6edc720218b256e72a7deecec"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
