[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/UNC6TW32w2fiCbp5pTUTt1K8b3x4hG7B"
  Md5 = "3a789cde96b71699f191230cea4ace34"
  Sha256 = "e47a80282bea946e7ad5a556355ad1963de3b9af62d03df8b50a1cca3b9f6b55"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/PyVFWgMNWGKNjedqRERFCNY9Vzabi2UE"
  Md5 = "a0645195037260be9c714d11f6747d93"
  Sha256 = "fe84d108bbe7946677b04590693edb717bcd48cafc0c723018d52ddaa742306e"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/LNvRw3nisJ3CD3SfPpnThXgJtGqm36ua"
  Md5 = "9064b20e3e0559befd6a5200453683ab"
  Sha256 = "0747e5045230abda9ae66fe0f11aaca474ec257a23c4c4fd3bf48f2b68e507b2"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
