[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/je6rbfg1evQFrJTVFEPSMnneDzcAK8Ca"
  Md5 = "65a84e1d8c323e96e052f9944d42079e"
  Sha256 = "1b0f32bd6f60ff0a3504112102b2f6db13ed4606ba2ab4278df2d42c05aa7241"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/5JZUhTugeHgpyN9KrVzdfhNBByx3wtMb"
  Md5 = "719e25896e74b2cf3796b5521ef5f3b8"
  Sha256 = "7e23a2cf5b62a954fbe55680bc727e235f7927515f966d5837f939b6a7af0fd4"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/8mBhrdWW7ELUfnm9pUDgmj7nXKHTwNk2"
  Md5 = "a88ac86060383fb552c191ad09b584ae"
  Sha256 = "42c0375d3d3cdef71dafa51dd48f14d762e8393c6e159999d59b41ae5ec0f7b4"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
