[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/fW3GwKrWN9h32zTRhLgVzMhXCFWUDgX7"
  Md5 = "3cc9e066005c0178af670e31fbdf4ae1"
  Sha256 = "dd81fde5eea6c70d62188b4ec9b688228e72261bac8d5f9bf7cf4751292abf50"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/RMvCztHJZndaStzfcewsgRdK5djbX2GF"
  Md5 = "6b59545c82bdd1bf8550cd63755ccbb5"
  Sha256 = "a033e8eca671298df752d24ce3776640deb7dfc741a480147d13b49726643bed"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/RjFqVYfpqpXqwGGUv8SXAUeCdEHh64DA"
  Md5 = "0a7b15b309661cee7d5584de54464563"
  Sha256 = "0580e20221afd51df93b7cf301c06a297491219cf4efc2dc0e7fe3b052579422"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
