[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/kMH9wrTtp3WZvEhwTBdRBWPw7a8KaakC"
  Md5 = "8cbaf6a670cde7e5f3c64a0a8a34cec9"
  Sha256 = "c5b5f034d5a4136ed57c26baf82ad1f2d8665da054070ca2cfe20e4d4f123dd3"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/Um4bLSaiVFXgGLZscJgXwc86kartTby2"
  Md5 = "82a465fdadb417e45fb45f3a75ca2779"
  Sha256 = "f82f3bdf355eb8f5800d7d263e119a2c6c860b8197cd0388ea4dec8333883a0b"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/QqWh6S3DRURFYAYMP6d1YYc3NZdcNPqK"
  Md5 = "8b034cea59ea46b32c498d1f11499fa2"
  Sha256 = "e82abf8dd49129619cc1f9e7867c5520a83a3cead3d9d4c62491046289cdf7b9"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
