[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/CVe47UbUZMUiJqHu4fYYsPGkcyGtW1N5"
  Md5 = "d73e64f66fa4cfccc54093230801d934"
  Sha256 = "e2c437dca9945572581f614c30e0d13463315e9aea7cb30bb602f5d7dc39b83b"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/yDJGidHXCQEpxNs9HL5WL7THdRDjN8Er"
  Md5 = "973b0018dbb529713f8fd9b458e529b9"
  Sha256 = "1cf914349057d7e98250c0cefa4b88f493a4582cce676506be30eee89240a0eb"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/MpvzUcYyZZY3S8hZfnzy5Tcb619NDDm7"
  Md5 = "61f7d392ddb72f22e46a5dfa2efcd351"
  Sha256 = "b6c7e5273ce95efb187e3b9f1f739019f67dfaf44702ebcf836df084e630c469"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
