[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/jmYMNfvW6eY36mJwL6prMDSJamT32TqW"
  Md5 = "4f898e3c63ef16de8ead6722e00355e5"
  Sha256 = "8c83f221b7ca4c132461325401909da9b74927129ad71d6aafc3cd6cacbe3432"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/Um4bLSaiVFXgGLZscJgXwc86kartTby2"
  Md5 = "82a465fdadb417e45fb45f3a75ca2779"
  Sha256 = "f82f3bdf355eb8f5800d7d263e119a2c6c860b8197cd0388ea4dec8333883a0b"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/QqWh6S3DRURFYAYMP6d1YYc3NZdcNPqK"
  Md5 = "8b034cea59ea46b32c498d1f11499fa2"
  Sha256 = "e82abf8dd49129619cc1f9e7867c5520a83a3cead3d9d4c62491046289cdf7b9"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
