[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/r8LTp7ityLmn7yHcSb4Rwd9CU4JRsDab"
  Md5 = "b365df787cb4529c55d1a46d8fc77dcf"
  Sha256 = "ab6f2e4df9dd68066a45460544be917e1ab03731eb34c1b077f65489112c5d40"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/MFd5VswkfehizktNFPFSTSCUSaxuzF9X"
  Md5 = "7d61c4f3c2ad5d783e852cb6520fc772"
  Sha256 = "7c6d2e82a753a90ddb2576e09dcd0bed89cdb0ab702754c769e4e6387678bf4a"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
