[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/avCxEzSeufXGpjgzgezVuxJisWKNpqSv"
  Md5 = "922b91398f7798ec4518345e9c0a35d3"
  Sha256 = "8e09114b9c7ca46a29dc592e2be8ddabc0e4d8f58a55abb790818c832e1cc7dc"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/TnQGJDPautHXeSccDmnpjNUyPRrKqPSh"
  Md5 = "e577ca896bb3a91a2fcc9fc07707a008"
  Sha256 = "040ebe1086ccceaec6d9e6ccb07615f177dbd2c6c464c7230b5fd87a859bfff6"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
