[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/YgmrQaMekXenZSJcPQMaaihLWinGGDZv"
  Md5 = "13a89146b7e43469dc38ad76a6e33057"
  Sha256 = "ccca73729bcda7bf79ed28d805174cb331f6b76dae2b191bb920f783f7a18945"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/XGhyLXkLRYBNaTyJYyGZXmhKFuGGffzd"
  Md5 = "de76fd6d1e61518840cc61313a15e2c3"
  Sha256 = "57c827ef713a0e60486e9a9c0c39cfea627550b3239754b636b7932de29b4647"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
