[server]
uri = "https://raw.githubusercontent.com/cootos/server/master/QDyRwAPteHwfqMEuRSNTCfNWDiZGXktq"
md5 = "1c9eb27f901b1be46bb2a2a037140427"
sha256 = "b3b8c348e162732848e2dfd3e21229775d5b3c1e7625627d3b3e51a91e221e23"

[rules]
uri = "https://raw.githubusercontent.com/cootos/server/master/VHTmXrWHiLXKiYCPrZzvEaxYgKbVBgni"
md5 = "7347538ef2cb0ad516ece8d9a8f88240"
sha256 = "f315c4a295125b76c10a5de8130c540467fd0f9dd47e7bfdcf98d602ef3893c0"

[geoip]
uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
sha256= ""
