[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/KQtfqCeeuxdhwws7vgjHDBsHQYuRDYeb"
  Md5 = "87705b23e627f89da6137c04b4d29dfd"
  Sha256 = "2343d7ffaef668d0b96dc255b169c33fe0b80ba4e0d8a5380a263b64eb0f4734"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/VK6vBtGaGPcuxmMp8MiMjq3JdG15YAFP"
  Md5 = "56115de04b453f1d9184bba304ce0825"
  Sha256 = "afeeeb11c7e0da9e288e91c778dd96c4a183f4ef5ffbd0c7e360dcdaa6afbd00"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/2QNWV6nG1YwwTWhNa9tTthxz1gPrEbbq"
  Md5 = "b3854d16c219a52f7bb250150ac7a203"
  Sha256 = "e471771bf24c11818cfe9b346029d2aadc5a608b96d9e8de4580e579e9edef15"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
