[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/XwbTacGHQsnZinMKTcYbryLyRvEhKDJs"
  Md5 = "c8c4dc28cf401cbe4a012e3e9532439e"
  Sha256 = "275f15597cd587165d86df2997dce2cf3082635a36dc09c7c86c50ccc434ac37"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/LTWJMSGdKPixwMRTUFdRqiUTRbayKCiF"
  Md5 = "9064f11d28c8174bbb39d07d2d977f1e"
  Sha256 = "3d466861d9f696adf0286cebb64d171b770b232c21cb441ed7e21bce150fc3d4"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
