[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/ezXtTDq9LyVXVdJxC6NvXr912hSpvUNa"
  Md5 = "60fb6dc2d244d568705d9d61b1f52dac"
  Sha256 = "2e5d31fce269577f4f0ea7ae8c6d45206edd992ad2b8f0db452193dc2f149040"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/yeWC4sqcgXtHQTzdqRsdX5AGGTPhWrU9"
  Md5 = "f2f50a992f53d6dbc187c726b4903b3c"
  Sha256 = "53376119f5e9eb24824e7e3d32ff06a937f252ed74b87ab5586a4d5c4572521c"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/2cspZ4DX4FgARDDdPz1dTANWn6P41LDJ"
  Md5 = "fa0af965eec180e89dbfb128afbe55f6"
  Sha256 = "c5ecacfb509d6fa3337c02597eb31a54e47c3c472cbe5ecba30404401757c8f9"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
