[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/fW3GwKrWN9h32zTRhLgVzMhXCFWUDgX7"
  Md5 = "3cc9e066005c0178af670e31fbdf4ae1"
  Sha256 = "dd81fde5eea6c70d62188b4ec9b688228e72261bac8d5f9bf7cf4751292abf50"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/RMvCztHJZndaStzfcewsgRdK5djbX2GF"
  Md5 = "6b59545c82bdd1bf8550cd63755ccbb5"
  Sha256 = "a033e8eca671298df752d24ce3776640deb7dfc741a480147d13b49726643bed"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/82nxFDSyL2GJGfWxPgTHf7mWVyKuXhHj"
  Md5 = "c6679895f98306abf6cc2c443efca814"
  Sha256 = "10972df6f4350ab15f94773df51c50e6217203e01628afeda71c5c435a5f836e"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
