[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/QaNXA34T2L4pBmcimdMtDF1DvDTFWz2C"
  Md5 = "2a61b0b94d210c90160d52e4556eeec6"
  Sha256 = "fad90cc26a107bd081acacb4a9e7709e537a9366325a6254788fcc555c3bb24c"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/PZaX22JCgMuAFvsHZT5A18KQFBVMDkxg"
  Md5 = "905be8eef44544be2d8cccc20e00d301"
  Sha256 = "6fac3984792cd3f1b4a9a37a5c85edf50607133f8ec56ef8259f0a7601661f39"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/ygnwWVMnR7CqSbBShst7uUW7tzaMta1U"
  Md5 = "67b848b6fa89b3d603f2af8f36f90f53"
  Sha256 = "c9b55d7cabbc54cf9f7bd065686c9dd459f87bde4ac54c0e6362d0206a2a2967"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
