[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/r8LTp7ityLmn7yHcSb4Rwd9CU4JRsDab"
  Md5 = "b365df787cb4529c55d1a46d8fc77dcf"
  Sha256 = "ab6f2e4df9dd68066a45460544be917e1ab03731eb34c1b077f65489112c5d40"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/ZhE5Bs4waQfEU6f4aArheEizbmGhZs1U"
  Md5 = "af0a0aa44884b841dd72a90f64455a94"
  Sha256 = "50b23077f7fea6798cb8cad55bc4e055883bd872d646be043f3c2f1e739af902"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
