[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/jrp41eXPDdTMUHVatecpu9gbtCYiNZL9"
  Md5 = "48b0011638352394f5df1bd51f0a14ae"
  Sha256 = "c05ca773bb239531c18886bb65acd9db00bd7b561032c4ae012286b0a889de6b"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/UNbNhbRX16GUMWgTxaBjwqjmJuiRLD4N"
  Md5 = "6c799222207bba525c4b442fef5ef63d"
  Sha256 = "6af93e74ddddb696eda3bbafa08fe46ba9ce85c634160cf47bd87086048baf2e"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/2cspZ4DX4FgARDDdPz1dTANWn6P41LDJ"
  Md5 = "fa0af965eec180e89dbfb128afbe55f6"
  Sha256 = "c5ecacfb509d6fa3337c02597eb31a54e47c3c472cbe5ecba30404401757c8f9"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
