[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/eTvjXHSUENrxvvTahG5Rn3reKpXNvEj4"
  Md5 = "c233cbdcb472af84bca012a08e1e9dbc"
  Sha256 = "459c48de8f55f923a96cc4e5c752617f59394ba174b8bfe0e4e631d0927e1970"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/HZNGryznDQGHpJQcL4DgKWi1iNLP9kpH"
  Md5 = "2792406bccfbdffded05aeebba583410"
  Sha256 = "cf5215344defe68e372505cbbb17ca9d2e303100263bf57571358b63ec207557"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/7P4ZfcxJ33eiVW6xmXStXLm6KbNNPcPi"
  Md5 = "58fba73eba6d27f5aa51056cb45a2359"
  Sha256 = "054aa9235c99e813b1c0809335c790996d321bb080889b6c70b5936b54964ea3"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
