[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/LQeCBMTQscBsHRCYHzDWD4XX1uM5jj9u"
  Md5 = "653d8812bb9be79f2d2942a43687487a"
  Sha256 = "924908dd2863330fa4c75ea2cacc0b075d32426ce097c6bb9fc92a1cf689feaa"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/ZVhejr6u9WpDihnysj31tWHaqXJFJVdr"
  Md5 = "4d86a9a6dd1af49d6c2c9c66dd8df1c1"
  Sha256 = "3ec77a5348afb802d68f8ab0c85644977e8ec910c36e151f97cfc57fe747eafb"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/Yax4RtErvTMYHVgmM91AnDx5f3rjJT7r"
  Md5 = "a94941daa50aa0f46ec19de3fc9ef784"
  Sha256 = "7b7ccafba025278712113c189faee513a2a26fbdad2db3882d021d45f792c504"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
