[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/URJnK5FvyEfLkUZBS6UcHrK5hbUtSB1j"
  Md5 = "4bd569d4a553ce3f6393b3cc4a15577c"
  Sha256 = "b604d4249a99a034c421d73a30fec52448e9c696fa9a17046bc848561574d85a"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/cVZQWbeXz5CK4zpsC2ETE8ucb2AGaRta"
  Md5 = "57d7fb2d7a10fc1a605d8cf6cd6905f0"
  Sha256 = "43e7a15ea23cd147a57246723a0af1a96fbbe1b5e245c8b2307101ac32240db8"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/itkrnw1T7Xm1YxmTRspUkBGvX11MYLgT"
  Md5 = "bd19abf651eacb1ef42acac1c0f9cb34"
  Sha256 = "a096e71fd1c35b70f795662382fa46d709483eb8a33e529fe881250df580a77c"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
