[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/pKefmVdDc6RMceVeRXbXdDgSTvqiwcXk"
  Md5 = "ef57c84f87d2d20453ecd9af2f9f7210"
  Sha256 = "c4f36bb4e79f95086550b7c7ca813a74f59630304cedc473ac092c1b2e8cecd3"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/cMutV2jmXb8m6TrfB5tQMArwnafwW67b"
  Md5 = "e887ad8cdf6b2d7db888f788b85c5652"
  Sha256 = "a275bfaeff973fd831067e52c26a45b984636b96742ecbc978ab642009cb9d89"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/jWffzZdG3j1LPsKGLf2LFSZtpRfhybzq"
  Md5 = "2d1200a1834c2ddd1b95ee1f236b1dfd"
  Sha256 = "793f90486a0f31ae13791d750e8e9036651e0c091d4db479042656ac0f39dd25"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
