[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/rdBwZSj4KMKABt8BmiynkhrL3PhbNRse"
  Md5 = "949dd81ba31e93a6182136b50ea4f097"
  Sha256 = "40c3846e7eace93bbdfc58f26a08489a38126afaff014f4e67f7749e6726b31c"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/iZPyXir3TixPCYUwV3MWxsHYiGp2ym4Z"
  Md5 = "285b1a43ff9519bfe3b14f9bc237905c"
  Sha256 = "389e4052f293cd1e9369afe4d1c21f7dd8447a52b170385b0435fd62ad98ca3c"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/aSb5QAm7cymUMXmizPXJn9UzaArPr2C3"
  Md5 = "983839cede573a6eec72b2fadab6d71f"
  Sha256 = "9848f597f95c69fedb8b10ecf6debfb4ce6d86becc15a990c398fb175da26838"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
