[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/KeRnPKNDg12rUP54LzKZHgg7nKXisCDz"
  Md5 = "3cba959e18f620e812f5897e004d696b"
  Sha256 = "10b47739481bdea360466edd52d9a8ddfbaf831c68c79a2c69b46b8706f3c4d2"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/P4qYVJtsm2SR15nmtHHx6stC4vXjjA7K"
  Md5 = "faddf9ad80462cfdd4ec5fcc2e31d4f0"
  Sha256 = "98724c43ef79c5bd336aac36d8de8dc1a434af0eaa3a8b873fdf62365625babb"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
  Sha256 = ""
