[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/dXc8bynRr2RAiwJ64CuGfyHj7Xs3rRcD"
  Md5 = "4b46cb45a153e1aa5d261f1a1f714d3f"
  Sha256 = "e9b52c0c1ddb98e6043be0cd48b751ce557b19bb333ecca39cd454d6624bab24"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/pcGLsXgEM9v9P4VZ71PTdbrnFJ7pApbf"
  Md5 = "9726ece3569f0919f3bac92ddaf5d228"
  Sha256 = "1b059bdbbec83fa01e931934c76a9237c4d244e3c0d990dab1138fe91d5617c3"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/XE8keXb5xW1Jqd8BVhLwYDiP2ALTLXZG"
  Md5 = "ec906710824fd6a17e8f964c46f45286"
  Sha256 = "1222ee25f31aa0fc2fc8c8c4ca0cbf45c299e7a28bd42602aaab4b6e2614f903"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
