[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/tczaAHL1wAeuZzx1fLrWgvApNYDV2Tmk"
  Md5 = "c00f0adb47291debf5814f9fd976feaf"
  Sha256 = "f85bbe52be6c9d2ff21652e1da4220b0347d3dc19ecafeeeb66b30702ea284ee"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/1j8CPtm73tjxuUmGxPCrnGQUkpkpPVhL"
  Md5 = "be1cf87d7d1bfdd3b8d4e47fc4c4be16"
  Sha256 = "56667a343c896429c91f1122dcd50210243572a39a28ddb8b02616d6da36198a"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/h1EkjfjwZADUXJiBnYLrT9h2Dw5xfUxT"
  Md5 = "90e13e16048e191eaf9a27d1dbfda596"
  Sha256 = "4ba5afd1d7a5d156653b671a1516f1fcacff3aecd0af473df0e200ae99140561"

[Geoip]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz"
  Md5 = "https://raw.githubusercontent.com/cootos/server/master/GeoLite2-Country.tar.gz.md5"
