[Server]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/HxpDxLvFGBCrTm6dPSZJBeAfUTscmAsP"
  Md5 = "cc853283938076be6ee84e0fd72a365e"
  Sha256 = "5130c3d6b6863344f577e370906a7d395721bd0bea20b5bef0fb90265f8cee84"

[Node]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/ausP4w3umLdLWmsqnkLstPWZKRnZfK7z"
  Md5 = "3e4ad586fd4f3dbdaa063bea9666d5b0"
  Sha256 = "bc2a6dd422afae3a6764771b1ffe8f6abfad65f0959f0888c2b73d500a6f26b2"

[Rules]
  Uri = "https://raw.githubusercontent.com/cootos/server/master/jWffzZdG3j1LPsKGLf2LFSZtpRfhybzq"
  Md5 = "2d1200a1834c2ddd1b95ee1f236b1dfd"
  Sha256 = "793f90486a0f31ae13791d750e8e9036651e0c091d4db479042656ac0f39dd25"

[Geoip]
  Uri = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz"
  Md5 = "https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz.md5"
